### ISSUE TITLE
Attack didn't work

### ISSUE THREAD

**Issue by MyStoryRaven** [FelisDevelopment/fdesx-pets#1]
When attack option is selected pet is runinng in oposite direction of the target.

**Comment by niunisas** [comment]
I guess you are selecting a player? Not an NPC?

**Comment by MyStoryRaven** [comment]
You have right, i can attack npc.

**Comment by iSentrie** [comment]
+1 players are not very happy without this feature being broken

**Comment by niunisas** [comment]
Attack was fixed. Please redownload main dependency from keymaster.
